#!/bin/bash

META=$(printf "%s" "$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:org.mpris.MediaPlayer2.Player string:Metadata)")

if [[ "$1" == "--title" ]]; then
    echo "[$META]" | sed -n '/title/{n;p}' | cut -d '"' -f 2
elif [[ "$1" == "--artist" ]]; then
    echo "[$META]" | sed -n '/artist/{n;n;p}' | cut -d '"' -f 2
elif [[ "$1" == "--get-art" ]]; then
    echo "[$META]" | sed -n '/artUrl/{n;p}' | cut -d '"' -f 2
fi